name: outfits69_app
description: A 69 Outfits UI Demo in Flutter
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
flutter:
  uses-material-design: true
  
  fonts:
    - family: MaterialIcons
    
  assets:
    - assets/products.json
    - assets/tshirt/women/1/1.jpg
    - assets/tshirt/women/1/2.jpg
    - assets/tshirt/women/1/3.jpg
    - assets/tshirt/women/1/4.jpg
    - assets/tshirt/women/2/1.jpg
    - assets/tshirt/women/2/2.jpg
    - assets/tshirt/women/2/3.jpg
    - assets/tshirt/women/2/4.jpg
    - assets/tshirt/women/3/1.jpg
    - assets/tshirt/women/3/2.jpg
    - assets/tshirt/women/3/3.jpg
    - assets/tshirt/women/3/4.jpg
    - assets/tshirt/men/1/1.jpg
    - assets/tshirt/men/1/2.jpg
    - assets/tshirt/men/1/3.jpg
    - assets/tshirt/men/1/4.jpg
    - assets/tshirt/men/2/1.jpg
    - assets/tshirt/men/2/2.jpg
    - assets/tshirt/men/2/3.jpg
    - assets/tshirt/men/2/4.jpg
    - assets/tshirt/men/3/1.jpg
    - assets/tshirt/men/3/2.jpg
    - assets/tshirt/men/3/3.jpg
    - assets/tshirt/men/3/4.jpg
    - assets/tshirt/kid/1/1.jpg
    - assets/tshirt/kid/1/2.jpg
    - assets/tshirt/kid/1/3.jpg
    - assets/tshirt/kid/1/4.jpg
    - assets/tshirt/kid/2/1.jpg
    - assets/tshirt/kid/2/2.jpg
    - assets/tshirt/kid/2/3.jpg
    - assets/tshirt/kid/2/4.jpg
    - assets/tshirt/kid/3/1.jpg
    - assets/tshirt/kid/3/2.jpg
    - assets/tshirt/kid/3/3.jpg
    - assets/tshirt/kid/3/4.jpg
    - assets/shoes/men/1/1.jpg
    - assets/shoes/men/1/2.jpg
    - assets/shoes/men/1/3.jpg
    - assets/shoes/men/1/4.jpg
    - assets/shoes/women/1/1.jpg
    - assets/shoes/women/1/2.jpg
    - assets/shoes/women/1/3.jpg
    - assets/shoes/women/1/4.jpg
    - assets/shoes/women/3/1.jpg
    - assets/shoes/women/3/2.jpg
    - assets/shoes/women/3/3.jpg
    - assets/shoes/women/3/4.jpg
    - assets/shoes/kid/1/1.jpg
    - assets/shoes/kid/1/2.jpg
    - assets/shoes/kid/1/3.jpg
    - assets/shoes/kid/1/4.jpg
    - assets/shoes/men/2/1.jpg
    - assets/shoes/men/2/2.jpg
    - assets/shoes/men/2/3.jpg
    - assets/shoes/men/2/4.jpg
    - assets/shoes/women/2/1.jpg
    - assets/shoes/women/2/2.jpg
    - assets/shoes/women/2/3.jpg
    - assets/shoes/women/2/4.jpg
    - assets/shoes/men/3/1.jpg
    - assets/shoes/men/3/2.jpg
    - assets/shoes/men/3/3.jpg
    - assets/shoes/men/3/4.jpg
    - assets/jacket/men/1/1.jpg
    - assets/jacket/men/1/2.jpg
    - assets/jacket/men/1/3.jpg
    - assets/jacket/men/1/4.jpg
    - assets/jacket/women/1/1.jpg
    - assets/jacket/women/1/2.jpg
    - assets/jacket/women/1/3.jpg
    - assets/jacket/women/1/4.jpg
    - assets/jacket/men/2/1.jpg
    - assets/jacket/men/2/2.jpg
    - assets/jacket/men/2/3.jpg
    - assets/jacket/men/2/4.jpg
    - assets/jacket/kid/1/1.jpg
    - assets/jacket/kid/1/2.jpg
    - assets/jacket/kid/1/3.jpg
    - assets/jacket/kid/1/4.jpg
    - assets/jacket/men/3/1.jpg
    - assets/jacket/men/3/2.jpg
    - assets/jacket/men/3/3.jpg
    - assets/jacket/men/3/4.jpg
    - assets/jacket/women/2/1.jpg
    - assets/jacket/women/2/2.jpg
    - assets/jacket/women/2/3.jpg
    - assets/jacket/women/2/4.jpg
    - assets/jacket/men/2/4.jpg
    - assets/jacket/men/2/3.jpg
    - assets/jacket/men/2/2.jpg
    - assets/jacket/men/2/1.jpg
    - assets/jacket/kid/2/1.jpg
    - assets/jacket/kid/2/2.jpg
    - assets/jacket/kid/2/3.jpg
    - assets/jacket/kid/2/4.jpg
    - assets/jacket/women/3/1.jpg
    - assets/jacket/women/3/2.jpg
    - assets/jacket/women/3/3.jpg
    - assets/jacket/women/3/4.jpg
    - assets/pant/men/1/1.jpg
    - assets/pant/men/1/2.jpg
    - assets/pant/men/1/3.jpg
    - assets/pant/men/1/4.jpg
    - assets/pant/men/2/1.jpg
    - assets/pant/men/2/2.jpg
    - assets/pant/men/2/3.jpg
    - assets/pant/men/2/4.jpg
    - assets/pant/men/3/1.jpg
    - assets/pant/men/3/2.jpg
    - assets/pant/men/3/3.jpg
    - assets/pant/men/3/4.jpg
    - assets/pant/women/1/1.jpg
    - assets/pant/women/1/2.jpg
    - assets/pant/women/1/3.jpg
    - assets/pant/women/1/4.jpg
    - assets/pant/women/2/1.jpg
    - assets/pant/women/2/2.jpg
    - assets/pant/women/2/3.jpg
    - assets/pant/women/2/4.jpg
    - assets/pant/women/3/1.jpg
    - assets/pant/women/3/2.jpg
    - assets/pant/women/3/3.jpg
    - assets/pant/women/3/4.jpg
    - assets/pant/kid/1/1.jpg
    - assets/pant/kid/1/2.jpg
    - assets/pant/kid/1/3.jpg
    - assets/pant/kid/1/4.jpg
    - assets/pant/kid/2/1.jpg
    - assets/pant/kid/2/2.jpg
    - assets/pant/kid/2/3.jpg
    - assets/pant/kid/2/4.jpg
    - assets/pant/kid/3/1.jpg
    - assets/pant/kid/3/2.jpg
    - assets/pant/kid/3/3.jpg
    - assets/pant/kid/3/4.jpg