workflows:
  ios-build:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter Dependencies
        script: flutter pub get

      - name: Build IPA
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
